bootstrap.servers=dev-kafka.net.plm.eds.com:9092

# The group.id should be different for each node in a clustered setup.
# It is not the same as was defined for Aggregator in application.yml,
# values should be different as they are different applications
group.id=petrclient

# Change default value in connectionId to your unique polarion instance
aggregator.connectionId=petr

# You can use the following propertis to configure secure access to the Kafka service
# security.protocol=
# sasl.mechanism=
# sasl.jaas.config=
# ssl.keystore.location=
# ssl.keystore.password=
# ssl.truststore.location=
# ssl.truststore.password=
